enum user_input_name{ACCEL, BRAKE, STEER, INPUT_SIZE};
enum torcs_output_name{CC_TRIGGER, LKAS_TRIGGER, SPEED, RPM, TRACK_ANGLE, TRACK_WIDTH, TRACK_FRICTION, YAW, DISTANCE, STEER_LOCK, PASSED_TIME, IS_RUNNING, OUTPUT_SIZE};
